### ISSUE TITLE
Did you release the labels of DF evaluation set？I can't find them.

### ISSUE THREAD

**Issue by LoveSiameseCat** [asvspoof-challenge/2021#10]

**Comment by TakHemlata** [comment]
Hello, 

Yes, you can find them here ([ASVspoof](https://www.asvspoof.org/))

Keys and metadata are now available: [LA](https://www.asvspoof.org/resources/LA-keys-stage-1.tar.gz), [PA](https://www.asvspoof.org/resources/PA-keys-stage-1.tar.gz) and [DF](https://www.asvspoof.org/resources/DF-keys-stage-1.tar.gz).

Thanks
