### ISSUE TITLE
how can i get the evaluation EER or mint-DCF of different codec set (C1-C7)? the label can not provide the codec information

### ISSUE THREAD

**Issue by alexw914** [asvspoof-challenge/2021#13]

**Comment by TonyWangX** [comment]
Hello, 

You can submit the score file to codalab, and it will return EERs over each condition. 

LA: https://competitions.codalab.org/competitions/35161
PA: https://competitions.codalab.org/competitions/35160
DF: https://competitions.codalab.org/competitions/35159

**Comment by alexw914** [comment]
okay，Thanks very much
