### ISSUE TITLE
Not available LA keys and metadata 2021

### ISSUE THREAD

**Issue by synchro10** [asvspoof-challenge/2021#16]
I'm trying to download https://www.asvspoof.org/asvspoof2021/LA-keys-full.tar.gz but Page Not Found

**Comment by TonyWangX** [comment]
sorry, it can be a temporary issue with the web server.
I will ask

**Comment by synchro10** [comment]
> sorry, it can be a temporary issue with the web server. I will ask

Thank you, metadata is already available!
