### ISSUE TITLE
Where to download PA_cm_protocols

### ISSUE THREAD

**Issue by GolferChen** [asvspoof-challenge/2021#17]
Hello, thanks for the code. I am running the baseline of PA. The evaluation requires a file named "ASVspoof2021_PA_cm_protocols/ASVspoof2021.PA.cm.eval.trl.txt", but I cannot find it anywhere. Has it been released and where should I access it? Thanks a lot.

**Comment by GolferChen** [comment]
The data downloaded in https://zenodo.org/record/4834716#.Y93NOXBByUl only contains the flac files.

**Comment by TonyWangX** [comment]
Hi @GolferChen 
The package on zendo only contains flac files when it was released during the challenge.

The label file was released later after the challenge. 
I think the one required by the code is the stage-1 key file: 
[LA](https://www.asvspoof.org/resources/LA-keys-stage-1.tar.gz), 
[PA](https://www.asvspoof.org/resources/PA-keys-stage-1.tar.gz),
[DF](https://www.asvspoof.org/resources/DF-keys-stage-1.tar.gz).
They are hosted on https://www.asvspoof.org/index2021.html
(I am not handling the this part, but I may be wrong. 
 Hi @TakHemlata, do you know who was working on this?)


Note that the label set with full meta-information and the code to evaluate pooled and decomposed EER and min-tDCF are here. Check https://github.com/asvspoof-challenge/2021/blob/aae41bb3f4f38795ebf6901c7bbf3461e4ad662b/README.md

**Comment by GolferChen** [comment]
Hi, @TonyWangX, thanks for the reply. You are right. Only the stage-1 key file is needed. I have successfully evaluated the performance of baselines. Thanks again.
