### ISSUE TITLE
Missing data in ASVspoof 2019 LA track?

### ISSUE THREAD

**Issue by nguyenvulong** [asvspoof-challenge/2021#18]
It has been 4 years and I hope that someone would realize this too: the line counts listed in `cm_protocols` do not match with the number of `.flac` files (in `dev` and `eval`) sub-datasets. Please see the screenshot below 👇 

(while I'm fine with data missing, my bigger concern is that: did this inconsistency cause any labeling issue, e.g., audio x is spoofed instead of bona fide because of this. I hope not)

<img width="585" alt="image" src="https://user-images.githubusercontent.com/1311412/217287302-a0ccc4c5-fb22-4dcb-9870-e40594277a5b.png">

**Comment by TonyWangX** [comment]
Hi @nguyenvulong, thanks for the message.

You know that ASVspoof means ASV and spoof.  

Have you checked the file list for ASV? 
The "missing numbers" are the files listed in LA/ASVspoof2019_LA_asv_protocols/*.eval.*.trn.txt.
They are for ASV enrollment and not used for spoofing CM.


```sh
$: cd LA/ASVspoof2019_LA_asv_protocols
$: cat *.dev.*.trn.txt | awk '{print $2}' | tr ',' '\n' | wc -l
142

$: cat *.eval.*.trn.txt | awk '{print $2}' | tr ',' '\n' | wc -l
696
```
24986 - 24844 = 142

71933 - 71237 = 696

The training set does not have ASV enrollment files.

**Comment by nguyenvulong** [comment]
Very nice. Thanks for your hard work. 👏
