### ISSUE TITLE
ASVspoof2021_LA_eval.tar.gz md5sum always different

### ISSUE THREAD

**Issue by zuowanbushiwo** [asvspoof-challenge/2021#19]
Hi
   I download data from this website https://zenodo.org/record/4837263#.Y-RL4nZBw2w, the tar file md5sum is always wrong?
   The picture after decompression is as follows, there are many strange files.
![image](https://user-images.githubusercontent.com/3354428/217709461-42756125-0e3b-4fa8-be86-861bf1c044a5.png)

   `2c84d173de8afbc2b84689a8670b9d32  ASVspoof2021_LA_eval.tar.gz`
   `  7785888412 2月   9 10:37 ASVspoof2021_LA_eval.tar.gz`
   thanks！

**Comment by TonyWangX** [comment]
Hi @zuowanbushiwo 
Sorry for the confusion. 

Zenodo website has a version control mechanism. 

I think the file you downloaded is from an early version ([10.5281/zenodo.4817651](https://zenodo.org/record/4817651)), which does has a md5sum of 2c84d173de8afbc2b84689a8670b9d32.

Could you confirm that you've downloaded the package from https://zenodo.org/record/4837263 ? 
On the right panel, you can see there are
```Versions
Version 1.1 10.5281/zenodo.4837263	May 28, 2021
Version 1.0 10.5281/zenodo.4817651	May 28, 2021
```

I think asvspoof.org shows the correct link to https://zenodo.org/record/4837263.
If you find the old link from somewhere, let us know. We will fix the link. 

Note that the md5sum is automatically computed by zenodo. Hence, if you download it from the correct link, the md5sum is supposed to be 2abee34d8b0b91159555fc4f016e4562.

**Comment by TonyWangX** [comment]
The ._ files are hidden file handler produced by the computer OS, on which the tar.gz package was created.
Apologize that they are in the package.  I think the correct version of the package will not contain them. 

See more on the file handlers here: 
https://apple.stackexchange.com/questions/14980

**Comment by zuowanbushiwo** [comment]
Thanks！ I downloaded from a wrong address, now I will try again with your above url.
