### ISSUE TITLE
Applying the pre-trained baseline model on my own dataset

### ISSUE THREAD

**Issue by zahrakhanjani128** [asvspoof-challenge/2021#23]
Hi again,
I am trying to apply the pre-trained DF baseline model (B03) on my own dataset. I have this error:
"
[91mNo input features found after scannning[0m
[91mPlease check ['/content/drive/MyDrive/MySelfVersionProjects/audio_sample/sample_set_3_split/Asvspoof2021_baseline_3_on_our_dataset/train_for_asvspoof2021_baseline'][0m
[91mThey should contain all files in file list[0m
[91mPlease also check filename extentions ['.flac'][0m
[91mThey should be correctly specified[0m
[91mError: Failed to read input features[0m"

The extension of my audio clips is .wav
Should I change them into .flac ?
What should I do to prepare my data for letting the model extract/read the input features?

**Comment by TonyWangX** [comment]
Simply change '.flac' with '.wav' in the configuration files.

https://github.com/asvspoof-challenge/2021/blob/aae41bb3f4f38795ebf6901c7bbf3461e4ad662b/DF/Baseline-LFCC-LCNN/project/baseline_DF/config_auto.py#L47

https://github.com/asvspoof-challenge/2021/blob/aae41bb3f4f38795ebf6901c7bbf3461e4ad662b/DF/Baseline-LFCC-LCNN/project/baseline_DF/config.py#L54

**Comment by zahrakhanjani128** [comment]
Thank you again!
The format issue is solved. I have the pre-trained model applied on my dataset, but it stopped in the middle of its process with this error below.  What the problem could be? It has processed half of the audio clips and gave me the scores for them (which is fascinating) , but stopped at a point. The error appeared in the log_eval.txt 
"
Traceback (most recent call last):
  File "/content/2021/DF/Baseline-LFCC-LCNN/project/baseline_DF/main.py", line 181, in <module>
    main()
  File "/content/2021/DF/Baseline-LFCC-LCNN/project/baseline_DF/main.py", line 175, in main
    nii_nn_wrapper.f_inference_wrapper(args, model, device, \
  File "/content/2021/DF/Baseline-LFCC-LCNN/core_scripts/nn_manager/nn_manager.py", line 506, in f_inference_wrapper
    for _, (data_in, data_tar, data_info, idx_orig) in \
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/2021/DF/Baseline-LFCC-LCNN/core_scripts/data_io/default_data_io.py", line 377, in __getitem__
    in_data[:,s_dim:e_dim] = tmp_d[s_idx:e_idx,:]
**ValueError: could not broadcast input array from shape (88200,2) into shape (88200,1)**
"

**Comment by TonyWangX** [comment]
It is like to be the issue with the number of channels in the audio.

The default configuration in config.py requires that the input audio file is mono channel (thus, dimension per time step is 1 https://github.com/asvspoof-challenge/2021/blob/aae41bb3f4f38795ebf6901c7bbf3461e4ad662b/DF/Baseline-LFCC-LCNN/project/baseline_DF/config.py#L49)

The error is likely to be caused by a stero audio file, which has 2 dimensions per time step. Thus, the data of shape (88200,2) cannot assigned to the tensor of shape (88200,1). 

Could you check the audio file format?

**Comment by zahrakhanjani128** [comment]
The audio format was originally .wav, but I checked .flac format as well and the error is the same. I kept out some suspicious  audio clips , to see if I can have the model ran on the remaining clips, still I have the same error! I am playing with the audio clips right now, and will update you soon.
Thank you so much!

**Comment by zahrakhanjani128** [comment]
I have a quick question irrelevant to this task. We eager to have you as a virtual guest speaker in our University lab (university of Maryland Baltimore County, MD, USA - MData Lab). I checked your blog, and could not find any direct contact information. Could you please give me your email address or email me to zkhanja1@umbc.edu for any further possible collaborations? I really appreciate it!
I will delete this comment from here, after creating the connection, to not make other people confused. 
Thanks again!

**Comment by TonyWangX** [comment]
> The audio format was originally .wav, but I checked .flac format as well and the error is the same. 

Hi, the issue is not being wav or flac. 
It is about the number of channels in the audio. 


If you use librosa, you can check this page https://librosa.org/doc/main/generated/librosa.to_mono.html. 
The stereo audio will have two dimensions per time step. 
You can use that command to convert the audio to mono. 


If you use sox (https://sox.sourceforge.net/) in terminal, you can check easily
```
$: soxi FILE.wav
...
Channels       : 1            <------ 1 or 2?
Sample Rate    : 24000
Precision      : 16-bit
...
```
Sox also supports converting the stereo into mono.

**Comment by zahrakhanjani128** [comment]
Many thanks for your valuable guidances! I changed them to Mono. However, now my Colab GPU is finished, and Google Colab does not renew it, although I waited for a couple of days!
Now, the error is:
"RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU."

Even they restricted the access to GPU with my other google accounts! 

I ran this code:

if torch.cuda.is_available():
    map_location=lambda storage, loc: storage.cuda()
else:
    map_location='cpu'

Nothing changed!

Could you please guide me where should I paste this piece of the code to work and let the code be ran on CPU? 
Thanks in advance!

**Comment by zahrakhanjani128** [comment]
Thank you for all of your responses, the model is applied on my dataset well.
