### ISSUE TITLE
How to download the ground-truth labels of the evaluation sets of this year

### ISSUE THREAD

**Issue by changtaoli** [asvspoof-challenge/2021#6]
I cannot access the keys, but something like this: 
`version https://git-lfs.github.com/spec/v1
oid sha256:466a73bff42ac654626e784d35ee990f596872e65705769a112e140c8a4d71b9
size 21255945`

**Comment by TonyWangX** [comment]
Hello, 
It seems that there is no git lfs installed on your PC?

The label files are saved through git lfs -- its size is larger than the limit.

Please install git lfs and clone the repo again. See tutorial here: https://github.com/git-lfs/git-lfs/wiki/Tutorial

**Comment by changtaoli** [comment]
> Hello, It seems that there is no git lfs installed on your PC?
> 
> The label files are saved through git lfs -- its size is larger than the limit.
> 
> Please install git lfs and clone the repo again. See tutorial here: https://github.com/git-lfs/git-lfs/wiki/Tutorial

Thank you so much for your kind reply!

**Comment by asvspoof-challenge** [comment]
Hello, apologize that our LFS quota is running out. (quicker than what we expected).

If you see errors using git lfs, please git pull the latest main branch. It will download the key files through the link on ASVspoof.org
